### ISSUE TITLE
[프론트] 스크롤바 관련 질문

### ISSUE THREAD

**Issue by eikjae** [TheWayYouWant/exercise-today#503]
In GitLab by @lyw6357 on May 7, 2022, 17:23

```css
// 스크롤바 안 보이게 하기
.body {
  -ms-overflow-style: none; /* IE, Edge */
  scrollbar-width: 0; /* Firefox */
}
::-webkit-scrollbar {
   /* Chrome, Safari, Opera */
  width: 0px;
}

::-webkit-scrollbar-thumb {
  background: #584491;
}
```

세로축 스크롤바가 없는 페이지와 있는 페이지가 있어서, <br>
홈페이지 상단에 고정된 헤더가 스크롤바로 인해 크기(width)가 바뀝니다.<br>
이를 방지하고자 세로축 스크롤바를 없앴는데 혹시 아예 스크롤바를 고정시키는 방법도 있는지,<br>
보통 웹사이트는 어떤식으로 해결하는지 궁금합니다.<br>
